// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucnhkvmazniihfdrhyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y25oa3ZtYXpuaWloZmRyaHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDA0OTIsImV4cCI6MjA3MTExNjQ5Mn0.BF_2RFgIZvEEDASHyuQq67bXOvGwhMDQVzC4CQigsYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});